### ISSUE TITLE
Hub image out of sync (missing 4.32.0)

### ISSUE THREAD

**Issue by cmaster11** [int128/gitbucket-docker#3]
https://hub.docker.com/r/int128/gitbucket/tags?page=1 does not contain latest 4.32.0 image. Maybe a broken build process?

**Comment by jarnfast** [comment]
Still an issue - the latest referred image (version 4.33.0) is not available on hub.docker.com. Have you had time to look into it @int128 ?

**Comment by int128** [comment]
I will take a look.

**Comment by int128** [comment]
It seems a link between Docker Hub and GitHub was broken. Rebuilding now.

**Comment by int128** [comment]
Now the images of 4.32.0 and 4.33.0 are available. Thank you for your contribution.
